// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Prefer local dev envs (e.g. Vercel/Neon) when present.
dotenv.config({ path: ".env.local" });
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer non-pgbouncer connection for schema/migration operations.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL"],
  },
});
